# Generated by Django 2.2.11 on 2020-04-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
